# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_test',
                'doc_host': 'https://ngupta23.github.io',
                'git_url': 'https://github.com/ngupta23/nbdev_test',
                'lib_path': 'nbdev_test'},
  'syms': { 'nbdev_test.core': {'nbdev_test.core.foo': ('core.html#foo', 'nbdev_test/core.py')},
            'nbdev_test.mytest': {'nbdev_test.mytest.say_hello': ('mytest.html#say_hello', 'nbdev_test/mytest.py')}}}
