"""This is the description of the code module"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_mytest.ipynb.

# %% auto 0
__all__ = ['say_hello']

# %% ../nbs/00_mytest.ipynb 3
def say_hello(
    to: str  # name of the person
) -> str:
    "Say hello to somebody"
    return f'Hello {to}!'
